# Generated by Django 5.2.7 on 2025-10-27 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('self_employed', models.CharField(max_length=5)),
                ('family_history', models.CharField(max_length=5)),
                ('treatment', models.CharField(max_length=5)),
                ('days_indoors', models.CharField(max_length=50)),
                ('growing_stress', models.CharField(max_length=50)),
                ('changes_habits', models.CharField(max_length=50)),
                ('mood_prediction', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mental.user')),
            ],
        ),
    ]
