# Generated by Django 5.2.7 on 2025-10-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental', '0002_surveyresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='Coping_Struggles',
            field=models.CharField(default='Medium', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='Mental_Health_Hist',
            field=models.CharField(default='Yes', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='Mood_Swings',
            field=models.CharField(default='Medium', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='Social_Weakness',
            field=models.CharField(default='yes', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='Work_Interest',
            field=models.CharField(default='no', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='care_options',
            field=models.CharField(default='Not sure', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='mental_health_interview',
            field=models.CharField(default='Maybe', max_length=5),
            preserve_default=False,
        ),
    ]
