# Generated by Django 5.2.7 on 2025-10-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental', '0003_surveyresponse_coping_struggles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='mood_score',
            field=models.IntegerField(null=True),
        ),
    ]
